name: Build on Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      release_title:
        description: 'Release Title'
        required: true
        type: string
      release_tag:
        description: 'Release Tag'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Display release information
      run: |
        echo "Building release: ${{ inputs.release_title }}"
        echo "Release tag: ${{ inputs.release_tag }}"
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build application
      run: dotnet build --configuration Release --no-restore
      
    - name: Publish application
      run: dotnet publish --configuration Release --no-build --output ./publish
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: published-app-${{ inputs.release_tag }}
        path: ./publish/